module.exports = {
    cpf: 'CPF precisa ter 11 digitos, diga negociar novamente para consulta',
    cpfinválido: 'CPF inválido',
    devolvido: 'Poxa !! Vi que retiram seu contrato daqui, vou pedir que procure a empresa credora',
    maiscontratos: 'Você tem mais de um contrato conosco, segue as informações',
    maiscontratos2:'Anote ou copie o código da empresa que quer negociar',
    maiscontratos3:'e depois digite a frase 👉"verificar código"👈 para continuar',
    errobuscarcpf1:'Não consegui encontrar o seu CPF. Pode ter acontecido o seguinte:',
    errobuscarcpf2:'➡Seu CPF não está em nossa base',
    errobuscarcpf3:'➡Caso indisponivel para negociar neste canal',
    errobuscarcpf4:'Caso queira tentar novamente é só dizer negociar',
    compreendemos:'Ok . . . compreendemos !\n Vou te passar os valores que constam em aberto, até a presente data.',
    askformadepgto:'Preciso saber a forma de pagamento? A vista ou Parcelado?',
    erroverificarcod:'O código que você me passou está errado ou indisponível para continuar',
    semcondicoes:'Ok, registrei que não tem condições, entraremos em contato em breve para conversar. Mantenha seu telefone ligado',
    contesta:'Registrei sua reclamação, estaremos avaliando com a empresa credora e entraremos em contato em breve para conversar. Mantenha seu telefone ligado',
    acordo:'Formalizei seu acordo, aguarde que em breve o boleto estará disponível em:',
    avisoacordo1:'⚠Atenção, caso não ocorra o pagamento até o vencimento',
    avisoacordo2:' as condições aqui formalizadas serão perdidas⚠',
    telsduvidas:'Dúvidas? me ligue ☎️',
    errogravarac:'Não consegui gravar o seu acordo, vou precisar que ligue para',
    tels:'Se já quiser conversar com a gente os telefones são',
    meliga:'Vou pedir para ligar no',
    errorenvio:'Não consegui solicitar o reenvio do boleto, vou pedir que entre em contato no',
    errogeral:'Ops, seu contrato foi bloqueado, vou pedir que ligue urgente para',
    askrecebeublt:'Recebeu o boleto? Caso não é só dizer "não recebi o boleto"',
    naoavista:'Infelizmente não consegui parcelar o seu contrato. Diga a vista para seguirmos com a negociação',
    melhorproposta:'Esta é a melhor proposta possível para seu contrato, diga sim para formalizar o acordo',
    semdesconto:'Juro que tentei um desconto mas não foi autorizado',
    askregistraac:'Podemos registrar seu acordo?',
    errosolicita:'nâo conseguir seguir com a solicitação, tente mais tarde',
    falhareenvio:' Ops,não consegui reenviar o seu boleto, favor entre em contato conosco.tels:',
    melhorproposta:'Infelizmente não consegui😔. Fiz até um esforço mas a melhor proposta parcelada foi a que te disse antes',
    melhorproposta1:'Ei, aproveite antes que mudem a proposta, diga parcelado para continuarmos com aquela negociação',
    melhorparcelado:'Infelizmente não consegui😔. Fiz até um esforço mas a melhor proposta parcelada foi a que te disse antes',
    errogenerico:'Não consegui processar esta solicitação, tente mais tarde',
    solicreenvio:'já solicitei que reenviem o boleto no seu email:',
    falarconosco:'Caso queira entrar em contato conosco de imediato pode ligar no'
}